SECTION_WEIGHTS = {
    "skills":      0.35,
    "projects":    0.35,
    "experience":  0.20,
    "education":   0.10,
}

AIML_SKILLS = {
    "Python": 10,
    "PyTorch": 15,
    "TensorFlow": 15,
    "Machine Learning": 12,
    "Deep Learning": 15,
    "NLP": 18,
    "Transformers": 20,
    "LangChain": 15,
    "RAG": 18,
    "Docker": 10,
    "FastAPI": 10,
    "Computer Vision": 12,
    "Pandas": 8,
    "NumPy": 8,
    "Scikit-learn": 10,
    "HuggingFace": 15,
    "ONNX": 8,
    "CUDA": 10,
    "Keras": 10,
    "OpenCV": 10,
    "Matplotlib": 6,
    "Seaborn": 6,
    "SQL": 8,
    "Git": 6,
    "Linux": 6,
    "AWS": 10,
    "GCP": 10,
    "MLflow": 12,
    "Weights & Biases": 10,
    "FAISS": 14,
    "ChromaDB": 12,
    "Pinecone": 12,
    "Streamlit": 8,
    "Gradio": 8,
    "Stable Diffusion": 14,
    "Prompt Engineering": 12,
    "fine-tuning": 18,
    "LoRA": 16,
    "PEFT": 14,
}

AIML_PROJECT_KEYWORDS = {
    "RAG": 20,
    "Transformers": 20,
    "LLM": 20,
    "LangChain": 15,
    "FastAPI": 10,
    "PyTorch": 15,
    "Docker": 10,
    "Computer Vision": 15,
    "NLP": 15,
    "fine-tuning": 20,
    "embedding": 15,
    "vector database": 18,
    "retrieval": 16,
    "chatbot": 12,
    "classification": 12,
    "detection": 12,
    "segmentation": 14,
    "summarization": 14,
    "question answering": 16,
    "sentiment": 12,
    "recommendation": 14,
    "deployed": 16,
    "API": 10,
    "dataset": 10,
    "accuracy": 10,
    "F1": 10,
    "benchmark": 14,
    "real-time": 14,
    "scalable": 14,
    "pipeline": 12,
}

AIML_EXPERIENCE_KEYWORDS = {
    "Intern": 10,
    "Machine Learning": 20,
    "Deep Learning": 20,
    "NLP": 20,
    "Transformers": 25,
    "PyTorch": 15,
    "TensorFlow": 15,
    "Research": 15,
    "model deployment": 20,
    "data scientist": 20,
    "AI engineer": 20,
    "MLOps": 18,
    "model training": 16,
}

SDE_SKILLS = {
    "C++": 15,
    "Java": 15,
    "DBMS": 12,
    "Operating Systems": 12,
    "Computer Networks": 10,
    "DSA": 20,
    "REST API": 10,
    "Node.js": 10,
    "Express.js": 10,
    "SQL": 10,
    "MongoDB": 8,
    "Docker": 10,
    "Git": 6,
    "React": 8,
    "System Design": 15,
    "Kubernetes": 12,
    "Redis": 10,
    "GraphQL": 8,
    "PostgreSQL": 10,
    "TypeScript": 10,
    "Go": 12,
    "Rust": 12,
    "Spring Boot": 10,
    "Django": 10,
    "Flask": 8,
    "AWS": 12,
    "CI/CD": 10,
    "Linux": 8,
    "Kafka": 12,
    "gRPC": 12,
}

SDE_PROJECT_KEYWORDS = {
    "REST API": 15,
    "Microservices": 20,
    "Docker": 10,
    "React": 10,
    "Node.js": 15,
    "Database": 10,
    "Authentication": 10,
    "Scalable": 20,
    "CI/CD": 15,
    "Load balancing": 18,
    "deployed": 16,
    "real-time": 14,
    "WebSocket": 14,
    "OAuth": 12,
    "caching": 12,
    "queue": 12,
    "distributed": 18,
    "high availability": 18,
    "API gateway": 14,
    "testing": 10,
}

SDE_EXPERIENCE_KEYWORDS = {
    "Intern": 10,
    "Backend": 20,
    "API": 15,
    "Database": 15,
    "System Design": 20,
    "Microservices": 20,
    "React": 10,
    "Frontend": 12,
    "Full Stack": 15,
    "DevOps": 15,
    "SRE": 15,
    "software engineer": 20,
}

CGPA_SCORE_MAP = {
    (9.0, 10.1): 100,
    (8.5, 9.0):  90,
    (8.0, 8.5):  80,
    (7.5, 8.0):  70,
    (7.0, 7.5):  60,
    (0.0, 7.0):  40,
}

TIER1_INSTITUTES = [
    "iit", "nit", "bits", "iisc", "iiit", "iitdh", "iitb", "iitd",
    "iitm", "iitk", "iith", "iitg", "iitr", "iitbhu", "iitj", "iiti",
]

WEAK_BULLET_PATTERNS = [
    r"\bworked on\b",
    r"\bhelped (with|in)\b",
    r"\bresponsible for\b",
    r"\bwas involved\b",
    r"\bassisted\b",
    r"\bcontributed to\b",
    r"\bdid\b",
    r"\bhandled\b",
]

STRONG_BULLET_PATTERNS = [
    r"\b\d+\s*%\b",
    r"\breduced\b",
    r"\bimproved\b",
    r"\bincreased\b",
    r"\bachieved\b",
    r"\bbuilt\b",
    r"\bdeployed\b",
    r"\bdesigned\b",
    r"\boptimized\b",
    r"\bautomated\b",
    r"\bscaled\b",
    r"\barchitected\b",
]

PROJECT_COMPLEXITY_SIGNALS = {
    "deployed": 15,
    "production": 15,
    "real-time": 12,
    "scalable": 12,
    "distributed": 15,
    "API": 8,
    "docker": 10,
    "kubernetes": 15,
    "database": 8,
    "authentication": 8,
    "pipeline": 10,
    "automated": 10,
    "tested": 8,
    "CI/CD": 12,
    "users": 10,
    "requests": 10,
    "latency": 12,
    "accuracy": 10,
    "benchmark": 12,
    "open source": 15,
    "github": 8,
    "million": 15,
    "thousand": 10,
}